# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Deleted'), (3, 'Changed')])),
                ('file_name', models.TextField()),
                ('prev_size', models.IntegerField(null=True)),
                ('next_size', models.IntegerField(null=True)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'log records',
            },
        ),
    ]
